"""Initial schema

Revision ID: afbc6faa21a5
Revises: 
Create Date: 2026-05-03 07:53:21.155727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbc6faa21a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_year', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_academic_year_label', ['label'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('_student_exam_idx'))
        batch_op.create_unique_constraint('_student_exam_uc', ['student_id', 'exam_schedule_id'])

    with op.batch_alter_table('dummy_sticker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('_stu_exam_dummy_idx'))
        batch_op.create_unique_constraint('_stu_exam_dummy_uc', ['student_id', 'exam_schedule_id'])

    with op.batch_alter_table('foil_mark', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('_dummy_course_idx'))
        batch_op.create_unique_constraint('_dummy_course_uc', ['dummy_number', 'course_id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('result_published')

    with op.batch_alter_table('foil_mark', schema=None) as batch_op:
        batch_op.drop_constraint('_dummy_course_uc', type_='unique')
        batch_op.create_index(batch_op.f('_dummy_course_idx'), ['dummy_number', 'course_id'], unique=1)

    with op.batch_alter_table('dummy_sticker', schema=None) as batch_op:
        batch_op.drop_constraint('_stu_exam_dummy_uc', type_='unique')
        batch_op.create_index(batch_op.f('_stu_exam_dummy_idx'), ['student_id', 'exam_schedule_id'], unique=1)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('_student_exam_uc', type_='unique')
        batch_op.create_index(batch_op.f('_student_exam_idx'), ['student_id', 'exam_schedule_id'], unique=1)

    with op.batch_alter_table('academic_year', schema=None) as batch_op:
        batch_op.drop_constraint('uq_academic_year_label', type_='unique')

    # ### end Alembic commands ###
